# Generated by Django 5.0.3 on 2024-03-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourisme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetouristique',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
