# Generated by Django 5.0.3 on 2024-04-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourisme', '0003_guide_hebergement_location_sitetour_sitetouretguide_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketbus',
            name='date',
        ),
        migrations.AddField(
            model_name='ticketbus',
            name='bus',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketbus',
            name='depart',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketbus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Local/tourisme/photo'),
        ),
    ]
