# Generated by Django 5.0.3 on 2024-05-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourisme', '0004_remove_ticketbus_date_ticketbus_bus_ticketbus_depart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hebergement',
            name='categories',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketbus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tourisme\\photo'),
        ),
    ]
